[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pydork"
version = "1.1.7"
description = "Scraping and listing text and image searches on Google, Bing, DuckDuckGo, Baidu, Yahoo japan."
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.7"
license = {text = "MIT License"}
authors = [
  {name = "blacknon", email = "blacknon@orebibou.com"},
]
maintainers = [
  {name = "blacknon", email = "blacknon@orebibou.com"},
]
dependencies = [
  "beautifulsoup4",
  "chromedriver-autoinstaller",
  "fake-useragent",
  "geckodriver-autoinstaller",
  "lxml",
  "requests[socks]",
  "selenium==4.7.2",
  "selenium-requests",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
docs = [
  "sphinx",
  "sphinx-autobuild",
  "sphinx-rtd-theme",
]

[project.scripts]
pydork = "pydork:main"

[project.urls]
Homepage = "https://github.com/blacknon/pydork"

[tool.setuptools.packages.find]
include = ["pydork*"]

[tool.setuptools.data-files]
"etc/bash_completion.d" = ["completion/pydork-completion.bash"]
"share/zsh/site-functions" = ["completion/pydork-completion.bash", "completion/_pydork"]
